package com.uvg.directhealth.util;

public enum Specialty {
    GENERAL,
    CARDIOLOGY,
    DERMATOLOGY,
    ENDOCRINOLOGY,
    GASTROENTEROLOGY,
    GYNECOLOGY,
    HEMATOLOGY,
    INFECTIOLOGY,
    NEPHROLOGY,
    NEUROLOGY,
    PULMONOLOGY,
    OPHTHALMOLOGY,
    ONCOLOGY,
    ORTHOPEDICS,
    OTOLARYNGOLOGY,
    PEDIATRICS,
    PSYCHIATRY,
    RADIOLOGY,
    RHEUMATOLOGY,
    TRAUMATOLOGY,
    UROLOGY,
    ALLERGOLOGY,
    ANGIOLOGY,
    PLASTIC,
    GERIATRICS
}
